id: IADED7DAD
default_language: zh
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-09 14:54:55.015802
last_modified: 2023-02-09 14:54:55.015925
source_metadata:
  title: 'RK: Bodhisatvapiṭaka'
  language: zh
bases:
  7A46:
    base_file: 7A46.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
